### ISSUE TITLE
Transition issue 

### ISSUE THREAD

**Issue by sivert-io** [SivertGullbergHansen/IDG_gc_1007_gc_12_GuardiansOfCSS#56]
**Describe the bug**
Transition between Slide 11 and Slide 10 is incorrect. Slide 10 (function called slide11() ) displays the narration-text for Slide 11 when it is being run.

**To Reproduce**
1. Go to Slide 10, scroll towards Slide 11 and the narrator-text will already have the "fadein" selector applied before activating Slide11's function.

**Expected behavior**
When scrolling to a slide, the slide itself should add all styling to itself. Other slides should not add styles, only remove.

**Comment by TheRealJensJK** [comment]
Fix pushed, issue was that the slide 11() function had; `document.getElementById("slide11").getElementsByTagName("p")[0].classList.add("fadeIn");` insted of `document.getElementById("slide11").getElementsByTagName("p")[0].classList.remove("fadeIn");`, so the class was added prematurely
